# Generated by Django 4.1.7 on 2023-03-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hour', models.CharField(blank=True, max_length=200, null=True)),
                ('minute', models.CharField(blank=True, max_length=200, null=True)),
                ('ampm', models.CharField(blank=True, max_length=200, null=True)),
                ('recur_check', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
