# Generated by Django 4.1.7 on 2023-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testz',
            name='ampm',
        ),
        migrations.RemoveField(
            model_name='testz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='testz',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='testz',
            name='minute',
        ),
        migrations.AddField(
            model_name='testz',
            name='date_string',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
