# Generated by Django 4.1.7 on 2023-04-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_testz_ampm_remove_testz_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testz',
            name='end_date_string_array',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='testz',
            name='start_date_string_array',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
